// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwztgfsnqrssojnqxabx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53enRnZnNucXJzc29qbnF4YWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTYyODksImV4cCI6MjA2Nzc5MjI4OX0.T24vxp04TlURjLONRckQ3hiIKB1VUYFiFl0xGLNuDng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});